hibernate.connection.driver_class=org.sqlite.JDBC

hibernate.connection.url=jdbc:sqlite:data/game.db

hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

hibernate.hbm2ddl.auto=create
hibernate.show_sql=true